sudo: required
language: generic

services:
  - docker


before_install:
  - docker build -t furbo85/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true furbo85/docker-react npm run test

  deploy:
    provider: elasticbeanstalk
    region: "eu-north-1"
    app: "docker-react"
    env: "docker-react-env"
    bucket_name: "elasticbeanstalk-eu-north-1-777310446220"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_Access_key
    secret_access_key: "$AWS_secret_key"
